import { computeProration } from "@/lib/billing/proration";
import { computeLine } from "@/lib/billing/line";
import { resolveUnitPrice, type PriceRuleLike } from "@/lib/billing/pricing";
import type { ExceptionType } from "@prisma/client";

/**
 * Billing-run line generation.
 *
 * Given a billing period and a client's TD SYNNEX subscriptions, this produces
 * the proposed invoice lines plus a list of exceptions for anything that can't
 * be billed cleanly (unmapped SKU, unresolved price). It is pure so the preview
 * and the persisted run are generated by identical logic — what you review is
 * exactly what gets saved.
 */
export interface GenerationPeriod {
  start: Date;
  end: Date;
}

export interface SubscriptionInput {
  id: string;
  sku: string | null;
  productName: string | null;
  quantity: number;
  unitCost: number | null;
  currency: string | null;
  /** Subscription activation within/around the period (for proration). */
  activeStart?: Date | null;
  activeEnd?: Date | null;
}

export interface ProductMappingInput {
  /** SKU -> resolved QBO item. Absent entry => unmapped. */
  [sku: string]: { qboItemId: string | null; qboItemName: string | null };
}

export interface GeneratedLine {
  tdSynnexSubscriptionId: string;
  qboItemId: string | null;
  description: string;
  quantity: number;
  unitPrice: number;
  prorationFactor: number;
  proratedDays: number;
  periodDays: number;
  discount: number;
  adjustment: number;
  estimatedCost: number | null;
  subtotal: number;
  total: number;
}

export interface GenerationException {
  type: ExceptionType;
  message: string;
  sku?: string | null;
  subscriptionId?: string;
}

export interface GenerationResult {
  lines: GeneratedLine[];
  exceptions: GenerationException[];
}

export interface GenerateInput {
  clientId: string;
  period: GenerationPeriod;
  subscriptions: SubscriptionInput[];
  mappings: ProductMappingInput;
  priceRules: PriceRuleLike[];
}

export function generateBillingLines(input: GenerateInput): GenerationResult {
  const lines: GeneratedLine[] = [];
  const exceptions: GenerationException[] = [];

  for (const sub of input.subscriptions) {
    if (!sub.sku) {
      exceptions.push({
        type: "UNMAPPED_SKU",
        message: `Subscription ${sub.id} has no SKU and cannot be billed.`,
        subscriptionId: sub.id,
      });
      continue;
    }

    const mapping = input.mappings[sub.sku];
    if (!mapping || !mapping.qboItemId) {
      exceptions.push({
        type: "UNMAPPED_SKU",
        message: `SKU ${sub.sku} is not mapped to a QuickBooks item.`,
        sku: sub.sku,
        subscriptionId: sub.id,
      });
      continue;
    }

    const price = resolveUnitPrice({
      rules: input.priceRules,
      clientId: input.clientId,
      sku: sub.sku,
      baseCost: sub.unitCost,
    });
    if (price.unitPrice == null) {
      exceptions.push({
        type: "MISSING_PRICE",
        message: `No price rule resolves a unit price for SKU ${sub.sku}.`,
        sku: sub.sku,
        subscriptionId: sub.id,
      });
      continue;
    }

    const proration = computeProration({
      periodStart: input.period.start,
      periodEnd: input.period.end,
      activeStart: sub.activeStart,
      activeEnd: sub.activeEnd,
    });

    const { subtotal, total } = computeLine({
      quantity: sub.quantity,
      unitPrice: price.unitPrice,
      prorationFactor: proration.factor,
    });

    const estimatedCost =
      sub.unitCost != null
        ? round2(sub.unitCost * sub.quantity * proration.factor)
        : null;

    lines.push({
      tdSynnexSubscriptionId: sub.id,
      qboItemId: mapping.qboItemId,
      description:
        sub.productName ?? mapping.qboItemName ?? `SKU ${sub.sku}`,
      quantity: sub.quantity,
      unitPrice: price.unitPrice,
      prorationFactor: proration.factor,
      proratedDays: proration.billedDays,
      periodDays: proration.periodDays,
      discount: 0,
      adjustment: 0,
      estimatedCost,
      subtotal,
      total,
    });
  }

  return { lines, exceptions };
}

/** Sum the totals of generated lines (run grand total). */
export function sumLineTotals(lines: GeneratedLine[]): number {
  return round2(lines.reduce((acc, l) => acc + l.total, 0));
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}
